// Autogenerated code, do not change directly.
// To make changes to this file, please modify the templates at
// go-kit-middlewarer/tmpl/*.tmpl

// Package endpoint defines various different enpoint paths for transports
package endpoint

import (
	"github.com/wavecell/stringsvc"
)

const (
	// PathUppercase represents an endpoint path for Uppercase
	PathUppercase = "/stringservice/uppercase"
	// PathCount represents an endpoint path for Count
	PathCount = "/stringservice/count"
)

// StringServiceMiddleware defines a function that takes stringsvc.StringService and returns a stringsvc.StringService
type StringServiceMiddleware func(stringsvc.StringService) stringsvc.StringService
