// Autogenerated code, do not change directly.
// To make changes to this file, please modify the templates at
// go-kit-middlewarer/tmpl/*.tmpl

package transport

import (
	"net/http"

	"github.com/ayiga/go-kit-middlewarer/encoding"

	"github.com/wavecell/stringsvc"
)

var _ stringsvc.StringService

type embedMime struct {
	mime string
}

func (em *embedMime) GetMime() string {
	if em == nil || em.mime == "" {
		return "application/json"
	}

	return em.mime
}

func (em *embedMime) SetMime(mime string) {
	em.mime = mime
}

// uppercaseRequest defines a Request structure for the Method github.com/wavecell/stringsvc.StringService.Uppercase
type uppercaseRequest struct {
	*embedMime
	Str string `json:"str" xml:"str"`
}

// uppercaseResponse defines a Response structure for the Method github.com/wavecell/stringsvc.StringService.Uppercase
type uppercaseResponse struct {
	*embedMime
	Upper string `json:"upper" xml:"upper"`
	Err   error  `json:"err" xml:"err"`
}

// decodeUppercaseRequest creates a decoder for github.com/wavecell/stringsvc.StringService.Uppercase
func decodeUppercaseRequest(r *http.Request) (interface{}, error) {
	req := new(uppercaseRequest)
	req.embedMime = new(embedMime)
	return encoding.Default().DecodeRequest(req)(r)
}

// decodeUppercaseResponse creates a decoder for github.com/wavecell/stringsvc.StringService.Uppercase
func decodeUppercaseResponse(r *http.Response) (interface{}, error) {
	req := new(uppercaseResponse)
	req.embedMime = new(embedMime)
	return encoding.Default().DecodeResponse(req)(r)
}

// encodeUppercaseRequest creates an encoder for github.com/wavecell/stringsvc.StringService.Uppercase
func encodeUppercaseRequest(r *http.Request, request interface{}) error {
	return encoding.Default().EncodeRequest()(r, request)
}

// encodeUppercaseResponse creates an encoder for github.com/wavecell/stringsvc.StringService.Uppercase
func encodeUppercaseResponse(w http.ResponseWriter, response interface{}) error {
	return encoding.Default().EncodeResponse()(w, response)
}

// countRequest defines a Request structure for the Method github.com/wavecell/stringsvc.StringService.Count
type countRequest struct {
	*embedMime
	Str string `json:"str" xml:"str"`
}

// countResponse defines a Response structure for the Method github.com/wavecell/stringsvc.StringService.Count
type countResponse struct {
	*embedMime
	Count int `json:"count" xml:"count"`
}

// decodeCountRequest creates a decoder for github.com/wavecell/stringsvc.StringService.Count
func decodeCountRequest(r *http.Request) (interface{}, error) {
	req := new(countRequest)
	req.embedMime = new(embedMime)
	return encoding.Default().DecodeRequest(req)(r)
}

// decodeCountResponse creates a decoder for github.com/wavecell/stringsvc.StringService.Count
func decodeCountResponse(r *http.Response) (interface{}, error) {
	req := new(countResponse)
	req.embedMime = new(embedMime)
	return encoding.Default().DecodeResponse(req)(r)
}

// encodeCountRequest creates an encoder for github.com/wavecell/stringsvc.StringService.Count
func encodeCountRequest(r *http.Request, request interface{}) error {
	return encoding.Default().EncodeRequest()(r, request)
}

// encodeCountResponse creates an encoder for github.com/wavecell/stringsvc.StringService.Count
func encodeCountResponse(w http.ResponseWriter, response interface{}) error {
	return encoding.Default().EncodeResponse()(w, response)
}
